import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cars: Prisma.CarCreateManyInput[] = [
  {
    slug: "maruti-swift",
    name: "Maruti Swift",
    brand: "Maruti",
    model: "Swift",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1197,
    powerBhp: 80.46,
    torqueNm: 111.7,
    mileageCity: 20.5,
    mileageHighway: 24.8,
    seatingCapacity: 5,
    bootLitres: 265,
    groundClearance: 163,
    priceMin: 649000,
    priceMax: 964000,
    monthlyService: 2400,
    insuranceYear1: 21000,
    safetyRating: 3,
    depRate1Yr: 0.84,
    depRate3Yr: 0.68,
    depRate5Yr: 0.53,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj_JYNnZNYoLinkR8t5_8beeuImeDboKQ-sQ&s",
    pros: ["great fuel economy", "easy city driving", "low maintenance cost", "wide service network"],
    cons: ["rear seat comfort is average", "basic cabin quality", "highway stability could improve"],
    tags: ["city", "budget", "family"]
  },
  {
    slug: "hyundai-i20",
    name: "Hyundai i20",
    brand: "Hyundai",
    model: "i20",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 86.76,
    torqueNm: 114.7,
    mileageCity: 16.8,
    mileageHighway: 20.2,
    seatingCapacity: 5,
    bootLitres: 311,
    groundClearance: 170,
    priceMin: 704000,
    priceMax: 1174000,
    monthlyService: 2700,
    insuranceYear1: 24000,
    safetyRating: 3,
    depRate1Yr: 0.82,
    depRate3Yr: 0.66,
    depRate5Yr: 0.5,
    imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/158139/i20-n-line-exterior-right-front-three-quarter-16.png?isig=0&q=80",
    pros: ["premium interiors", "feature loaded variants", "refined petrol engine", "good boot space"],
    cons: ["not the most fuel efficient", "rear headroom is tight"],
    tags: ["city", "sporty", "family"]
  },
  {
    slug: "tata-altroz",
    name: "Tata Altroz",
    brand: "Tata",
    model: "Altroz",
    year: 2024,
    type: "Hatchback",
    fuelType: "CNG",
    transmission: "Manual",
    engineCC: 1199,
    powerBhp: 86.79,
    torqueNm: 115,
    mileageCity: 17.2,
    mileageHighway: 21,
    seatingCapacity: 5,
    bootLitres: 345,
    groundClearance: 165,
    priceMin: 665000,
    priceMax: 1109000,
    monthlyService: 2600,
    insuranceYear1: 23000,
    safetyRating: 5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.48,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tata/Altroz/12614/1770888054138/front-left-side-47.jpg",
    pros: ["5-star safety rating", "solid build quality", "large boot for hatchback", "comfortable ride"],
    cons: ["engine feels less punchy", "service quality varies by city"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "maruti-baleno",
    name: "Maruti Baleno",
    brand: "Maruti",
    model: "Baleno",
    year: 2024,
    type: "Hatchback",
    fuelType: "CNG",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 88.5,
    torqueNm: 113,
    mileageCity: 20.1,
    mileageHighway: 23.7,
    seatingCapacity: 5,
    bootLitres: 318,
    groundClearance: 170,
    priceMin: 666000,
    priceMax: 988000,
    monthlyService: 2350,
    insuranceYear1: 21500,
    safetyRating: 3,
    depRate1Yr: 0.84,
    depRate3Yr: 0.69,
    depRate5Yr: 0.54,
    imageUrl: "https://imgd.aeplcdn.com/642x336/n/cw/ec/102663/baleno-exterior-right-front-three-quarter-69.png?isig=0&q=80",
    pros: ["excellent mileage", "spacious rear seat", "smooth automatic option", "low running costs"],
    cons: ["safety rating could be better", "steering feedback is light"],
    tags: ["city", "family", "budget"]
  },
  {
    slug: "honda-jazz",
    name: "Honda Jazz",
    brand: "Honda",
    model: "Jazz",
    year: 2023,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1199,
    powerBhp: 88.5,
    torqueNm: 110,
    mileageCity: 16.2,
    mileageHighway: 19.8,
    seatingCapacity: 5,
    bootLitres: 354,
    groundClearance: 165,
    priceMin: 821000,
    priceMax: 989000,
    monthlyService: 2500,
    insuranceYear1: 22000,
    safetyRating: 4,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/Jazz/6489/1677825341880/front-left-side-47.jpg",
    pros: ["very practical cabin", "magic seats flexibility", "reliable ivtec engine"],
    cons: ["older design", "limited variant choices", "discontinued in many markets"],
    tags: ["family", "city", "spacious"]
  },
  {
    slug: "honda-city",
    name: "Honda City",
    brand: "Honda",
    model: "City",
    year: 2024,
    type: "Sedan",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 119.35,
    torqueNm: 145,
    mileageCity: 15.5,
    mileageHighway: 18.9,
    seatingCapacity: 5,
    bootLitres: 506,
    groundClearance: 165,
    priceMin: 1190000,
    priceMax: 1625000,
    monthlyService: 3000,
    insuranceYear1: 32000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.64,
    depRate5Yr: 0.49,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/City/12093/1755764990493/front-left-side-47.jpg",
    pros: ["premium cabin feel", "class-leading rear space", "refined engine", "big boot"],
    cons: ["lower variants miss features", "ground clearance is moderate"],
    tags: ["family", "highway", "spacious"]
  },
  {
    slug: "maruti-ciaz",
    name: "Maruti Ciaz",
    brand: "Maruti",
    model: "Ciaz",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1462,
    powerBhp: 103.25,
    torqueNm: 138,
    mileageCity: 17.4,
    mileageHighway: 21.1,
    seatingCapacity: 5,
    bootLitres: 510,
    groundClearance: 170,
    priceMin: 930000,
    priceMax: 1229000,
    monthlyService: 2500,
    insuranceYear1: 26000,
    safetyRating: 4,
    depRate1Yr: 0.83,
    depRate3Yr: 0.67,
    depRate5Yr: 0.52,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/48542/ciaz-exterior-right-side-view.jpeg?q=80&q=80",
    pros: ["great mileage for sedan", "comfortable rear seat", "low upkeep cost"],
    cons: ["interior design feels dated", "limited engine options"],
    tags: ["family", "highway", "budget"]
  },
  {
    slug: "hyundai-verna",
    name: "Hyundai Verna",
    brand: "Hyundai",
    model: "Verna",
    year: 2024,
    type: "Sedan",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.57,
    torqueNm: 253,
    mileageCity: 14.1,
    mileageHighway: 18.3,
    seatingCapacity: 5,
    bootLitres: 528,
    groundClearance: 165,
    priceMin: 1100000,
    priceMax: 1787000,
    monthlyService: 3200,
    insuranceYear1: 34000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.47,
    imageUrl: "https://imgd.aeplcdn.com/642x336/n/cw/ec/41197/hyundai-verna-right-front-three-quarter7.jpeg?q=80",
    pros: ["powerful turbo engine", "segment-best features", "large boot space", "good safety package"],
    cons: ["design may not suit everyone", "rear headroom is average"],
    tags: ["sporty", "highway", "family"]
  },
  {
    slug: "skoda-slavia",
    name: "Skoda Slavia",
    brand: "Skoda",
    model: "Slavia",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.51,
    torqueNm: 250,
    mileageCity: 14.6,
    mileageHighway: 19.2,
    seatingCapacity: 5,
    bootLitres: 521,
    groundClearance: 179,
    priceMin: 1069000,
    priceMax: 1869000,
    monthlyService: 3500,
    insuranceYear1: 36000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Skoda/Slavia/11810/1762938173534/front-left-side-47.jpg",
    pros: ["strong performance", "european driving dynamics", "huge boot capacity"],
    cons: ["maintenance cost is higher", "rear seat width is average"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "volkswagen-virtus",
    name: "VW Virtus",
    brand: "Volkswagen",
    model: "Virtus",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.5,
    torqueNm: 250,
    mileageCity: 14.4,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 521,
    groundClearance: 179,
    priceMin: 1156000,
    priceMax: 1939000,
    monthlyService: 3600,
    insuranceYear1: 37000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://imgd.aeplcdn.com/642x361/n/cw/ec/184551/volkswagen-virtus-right-front-three-quarter0.jpeg?isig=0&q=75",
    pros: ["great high-speed stability", "solid build quality", "powerful gt variant", "large boot"],
    cons: ["service network is smaller", "top variants are expensive"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "tata-nexon",
    name: "Tata Nexon",
    brand: "Tata",
    model: "Nexon",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Manual",
    engineCC: 1199,
    powerBhp: 118.27,
    torqueNm: 170,
    mileageCity: 16.1,
    mileageHighway: 20.2,
    seatingCapacity: 5,
    bootLitres: 382,
    groundClearance: 208,
    priceMin: 799000,
    priceMax: 1499000,
    monthlyService: 2800,
    insuranceYear1: 26000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.65,
    depRate5Yr: 0.49,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/141867/nexon-exterior-right-front-three-quarter-79.png?isig=0&q=80&q=80",
    pros: ["5-star safety", "high ground clearance", "feature-rich trims", "strong road presence"],
    cons: ["cabin ergonomics need improvement", "after-sales inconsistency"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "maruti-brezza",
    name: "Maruti Brezza",
    brand: "Maruti",
    model: "Brezza",
    year: 2024,
    type: "SUV",
    fuelType: "CNG",
    transmission: "Automatic",
    engineCC: 1462,
    powerBhp: 101.65,
    torqueNm: 136.8,
    mileageCity: 17.2,
    mileageHighway: 20.1,
    seatingCapacity: 5,
    bootLitres: 328,
    groundClearance: 198,
    priceMin: 834000,
    priceMax: 1398000,
    monthlyService: 2500,
    insuranceYear1: 25000,
    safetyRating: 4,
    depRate1Yr: 0.84,
    depRate3Yr: 0.68,
    depRate5Yr: 0.54,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-zHg3VfFFCOh0fwENPRGUKwXhIi8nt4pSWw&s",
    pros: ["reliable ownership", "good mileage", "wide service reach"],
    cons: ["boot space is average", "interior quality is decent not premium"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "hyundai-venue",
    name: "Hyundai Venue",
    brand: "Hyundai",
    model: "Venue",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 998,
    powerBhp: 118.41,
    torqueNm: 172,
    mileageCity: 15.8,
    mileageHighway: 19.4,
    seatingCapacity: 5,
    bootLitres: 350,
    groundClearance: 190,
    priceMin: 794000,
    priceMax: 1362000,
    monthlyService: 2750,
    insuranceYear1: 25500,
    safetyRating: 4,
    depRate1Yr: 0.82,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://www.carandbike.com/_next/image?url=https%3A%2F%2Fimages.carandbike.com%2Fcar-images%2Fgallery%2Fhyundai%2Fvenue%2Fexterior%2Fhyundai_venue_sideview.jpg%3Fv%3D1763533769&w=640&q=90",
    pros: ["compact and easy to park", "feature-packed cabin", "refined turbo engine"],
    cons: ["rear space is tight for three", "ride can feel firm"],
    tags: ["city", "sporty", "budget"]
  },
  {
    slug: "kia-sonet",
    name: "Kia Sonet",
    brand: "Kia",
    model: "Sonet",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 998,
    powerBhp: 118.36,
    torqueNm: 172,
    mileageCity: 15.6,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 385,
    groundClearance: 205,
    priceMin: 799000,
    priceMax: 1550000,
    monthlyService: 2900,
    insuranceYear1: 27000,
    safetyRating: 3.5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.48,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/174423/sonet-exterior-left-front-three-quarter.jpeg?isig=0&q=80&q=80",
    pros: ["premium cabin design", "many transmission options", "good feature list", "strong urban appeal"],
    cons: ["rear seat is not the widest", "suspension is on firmer side"],
    tags: ["city", "sporty", "family"]
  },
  {
    slug: "mahindra-xuv300",
    name: "Mahindra XUV300",
    brand: "Mahindra",
    model: "XUV300",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1197,
    powerBhp: 108.59,
    torqueNm: 200,
    mileageCity: 15,
    mileageHighway: 18.1,
    seatingCapacity: 5,
    bootLitres: 257,
    groundClearance: 180,
    priceMin: 799000,
    priceMax: 1449000,
    monthlyService: 2950,
    insuranceYear1: 26500,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.62,
    depRate5Yr: 0.46,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/XUV300/6794/1701855582193/front-left-side-47.jpg",
    pros: ["excellent safety score", "strong turbo torque", "stable ride quality"],
    cons: ["small boot space", "cabin feels dated"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "hyundai-creta",
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1497,
    powerBhp: 113.18,
    torqueNm: 143.8,
    mileageCity: 15.3,
    mileageHighway: 18.4,
    seatingCapacity: 5,
    bootLitres: 433,
    groundClearance: 190,
    priceMin: 1100000,
    priceMax: 2000000,
    monthlyService: 3300,
    insuranceYear1: 36000,
    safetyRating: 3.5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.66,
    depRate5Yr: 0.51,
    imageUrl: "https://media.zigcdn.com/media/model/2026/Feb/front-1-4-left-1724564915_600x400.jpg",
    pros: ["segment benchmark features", "comfortable ride", "strong resale value", "good cabin quality"],
    cons: ["base variants miss features", "safety rating could be better"],
    tags: ["family", "city", "highway"]
  },
  {
    slug: "kia-seltos",
    name: "Kia Seltos",
    brand: "Kia",
    model: "Seltos",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.81,
    torqueNm: 253,
    mileageCity: 14.8,
    mileageHighway: 18.2,
    seatingCapacity: 5,
    bootLitres: 433,
    groundClearance: 190,
    priceMin: 1090000,
    priceMax: 2045000,
    monthlyService: 3400,
    insuranceYear1: 37000,
    safetyRating: 3.5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.49,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Kia/Seltos/7111/1678424780936/front-left-side-47.jpg",
    pros: ["powerful turbo option", "premium interiors", "advanced adas features", "great infotainment"],
    cons: ["ride quality is a bit stiff", "higher variants are pricey"],
    tags: ["sporty", "family", "highway"]
  },
  {
    slug: "tata-harrier",
    name: "Tata Harrier",
    brand: "Tata",
    model: "Harrier",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168.0,
    torqueNm: 350,
    mileageCity: 13.4,
    mileageHighway: 16.8,
    seatingCapacity: 5,
    bootLitres: 445,
    groundClearance: 205,
    priceMin: 1549000,
    priceMax: 2664000,
    monthlyService: 4200,
    insuranceYear1: 43000,
    safetyRating: 5,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsDXM_oJlzTY63PV8K5ED88I0Liczr0Pvthg&s",
    pros: ["solid road presence", "5-star safety", "strong diesel performance", "comfortable highway manners"],
    cons: ["city drivability can feel bulky", "higher maintenance than compact suvs"],
    tags: ["highway", "family", "spacious"]
  },
  {
    slug: "mg-hector",
    name: "MG Hector",
    brand: "MG",
    model: "Hector",
    year: 2024,
    type: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineCC: 1451,
    powerBhp: 141.04,
    torqueNm: 250,
    mileageCity: 12.8,
    mileageHighway: 15.7,
    seatingCapacity: 5,
    bootLitres: 587,
    groundClearance: 192,
    priceMin: 1399000,
    priceMax: 2259000,
    monthlyService: 4100,
    insuranceYear1: 42000,
    safetyRating: 3.5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.59,
    depRate5Yr: 0.43,
    imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/130583/hector-exterior-right-front-three-quarter-73.jpeg?isig=0&q=80",
    pros: ["massive cabin space", "huge touchscreen", "comfortable seats", "good highway cruiser"],
    cons: ["fuel efficiency is low", "soft handling around corners"],
    tags: ["spacious", "family", "highway"]
  },
  {
    slug: "mahindra-xuv700",
    name: "Mahindra XUV700",
    brand: "Mahindra",
    model: "XUV700",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2198,
    powerBhp: 182.38,
    torqueNm: 450,
    mileageCity: 13.2,
    mileageHighway: 16.6,
    seatingCapacity: 7,
    bootLitres: 240,
    groundClearance: 200,
    priceMin: 1399000,
    priceMax: 2649000,
    monthlyService: 4300,
    insuranceYear1: 45000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.47,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/XUV700/10794/1762509966753/front-left-side-47.jpg?tr=w-664",
    pros: ["strong performance options", "adas and tech loaded", "5-star safety", "available 7-seater"],
    cons: ["long waiting periods in some cities", "third row is best for kids"],
    tags: ["family", "highway", "spacious"]
  },
  {
    slug: "toyota-innova-crysta",
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2024,
    type: "MUV",
    fuelType: "Diesel",
    transmission: "Manual",
    engineCC: 2393,
    powerBhp: 147.51,
    torqueNm: 343,
    mileageCity: 11.4,
    mileageHighway: 14.3,
    seatingCapacity: 7,
    bootLitres: 300,
    groundClearance: 176,
    priceMin: 1999000,
    priceMax: 2699000,
    monthlyService: 4700,
    insuranceYear1: 49000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.69,
    depRate5Yr: 0.56,
    imageUrl: "https://mda.spinny.com/sp-file-system/public/2025-04-03/b895649aac3e40a0b692627684c0163a/raw/file.JPG",
    pros: ["legendary reliability", "very comfortable second row", "excellent resale value", "great long-distance comfort"],
    cons: ["pricey for features offered", "diesel only now"],
    tags: ["family", "spacious", "highway"]
  },
  {
    slug: "kia-carens",
    name: "Kia Carens",
    brand: "Kia",
    model: "Carens",
    year: 2024,
    type: "MUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.81,
    torqueNm: 253,
    mileageCity: 14.2,
    mileageHighway: 17.5,
    seatingCapacity: 7,
    bootLitres: 216,
    groundClearance: 195,
    priceMin: 1052000,
    priceMax: 1952000,
    monthlyService: 3400,
    insuranceYear1: 35000,
    safetyRating: 3,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.48,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuZ7bSPNjOan8_OeTbElOjK_1YD5m9ZpBrgQ&s",
    pros: ["great family practicality", "comfortable three rows", "feature rich cabin", "multiple powertrains"],
    cons: ["third-row boot space is limited", "not as rugged as suvs"],
    tags: ["family", "spacious", "city"]
  },
  {
    slug: "maruti-ertiga",
    name: "Maruti Ertiga",
    brand: "Maruti",
    model: "Ertiga",
    year: 2024,
    type: "MUV",
    fuelType: "CNG",
    transmission: "Manual",
    engineCC: 1462,
    powerBhp: 86.63,
    torqueNm: 121.5,
    mileageCity: 22.4,
    mileageHighway: 26.2,
    seatingCapacity: 7,
    bootLitres: 209,
    groundClearance: 185,
    priceMin: 869000,
    priceMax: 1330000,
    monthlyService: 2300,
    insuranceYear1: 23000,
    safetyRating: 3,
    depRate1Yr: 0.83,
    depRate3Yr: 0.67,
    depRate5Yr: 0.53,
    imageUrl: "https://5.imimg.com/data5/HX/OP/GLADMIN-13487668/maruti-ertiga-cat.png",
    pros: ["excellent value for large families", "very low running costs", "good comfort for segment"],
    cons: ["safety package is basic", "performance is modest when fully loaded"],
    tags: ["family", "budget", "spacious"]
  },
  {
    slug: "mahindra-scorpio-n",
    name: "Mahindra Scorpio-N",
    brand: "Mahindra",
    model: "Scorpio-N",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2198,
    powerBhp: 172.45,
    torqueNm: 400,
    mileageCity: 12.4,
    mileageHighway: 15.9,
    seatingCapacity: 7,
    bootLitres: 460,
    groundClearance: 187,
    priceMin: 1399000,
    priceMax: 2454000,
    monthlyService: 4100,
    insuranceYear1: 42000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.62,
    depRate5Yr: 0.46,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-4.png?isig=0&q=80&q=80",
    pros: ["strong road presence", "powerful engines", "good offroad capability", "robust build"],
    cons: ["body roll at speed", "fit and finish can vary"],
    tags: ["offroad", "family", "highway"]
  },
  {
    slug: "jeep-meridian",
    name: "Jeep Meridian",
    brand: "Jeep",
    model: "Meridian",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168,
    torqueNm: 350,
    mileageCity: 12.6,
    mileageHighway: 15.8,
    seatingCapacity: 7,
    bootLitres: 481,
    groundClearance: 214,
    priceMin: 3150000,
    priceMax: 3879000,
    monthlyService: 5600,
    insuranceYear1: 54000,
    safetyRating: 5,
    depRate1Yr: 0.76,
    depRate3Yr: 0.57,
    depRate5Yr: 0.42,
    imageUrl: "https://images.timesdrive.in/photo/msid-151013918,thumbsize-434500/151013918.jpg",
    pros: ["premium cabin finish", "proper suv stance", "stable highway behavior", "good safety kit"],
    cons: ["expensive to own", "third row best for children"],
    tags: ["luxury", "highway", "family"]
  },
  {
    slug: "tata-safari",
    name: "Tata Safari",
    brand: "Tata",
    model: "Safari",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168,
    torqueNm: 350,
    mileageCity: 13,
    mileageHighway: 16.3,
    seatingCapacity: 7,
    bootLitres: 420,
    groundClearance: 205,
    priceMin: 1619000,
    priceMax: 2769000,
    monthlyService: 4300,
    insuranceYear1: 44000,
    safetyRating: 5,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdARTKGho4ToEgLpEkaP7hjttGu88vxLP4_A&s",
    pros: ["captain-seat option", "5-star safety", "feature rich top trims", "strong highway comfort"],
    cons: ["third row space is average", "diesel-only lineup"],
    tags: ["family", "spacious", "highway"]
  },
  {
    slug: "skoda-kushaq",
    name: "Skoda Kushaq",
    brand: "Skoda",
    model: "Kushaq",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.51,
    torqueNm: 250,
    mileageCity: 14.7,
    mileageHighway: 18.6,
    seatingCapacity: 5,
    bootLitres: 385,
    groundClearance: 188,
    priceMin: 1089000,
    priceMax: 1880000,
    monthlyService: 3500,
    insuranceYear1: 36000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://cdn.skoda-auto.com/images/external/a720b3257fb9f34c9f582f866b15d4b7/DerivativeIntroductionModule/517a7c8aa96236dc9d8954f4916e42718d6bf87515b75d7ab74272b3bc3277bf/Default_bp1920_1.webp",
    pros: ["excellent driving dynamics", "strong safety package", "punchy turbo engines", "good highway confidence"],
    cons: ["rear seat is not the widest", "service cost is above average"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "hyundai-tucson",
    name: "Hyundai Tucson",
    brand: "Hyundai",
    model: "Tucson",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1999,
    powerBhp: 154.8,
    torqueNm: 192,
    mileageCity: 11.9,
    mileageHighway: 14.8,
    seatingCapacity: 5,
    bootLitres: 540,
    groundClearance: 192,
    priceMin: 2963000,
    priceMax: 3587000,
    monthlyService: 5200,
    insuranceYear1: 53000,
    safetyRating: 5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.58,
    depRate5Yr: 0.43,
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2026-hyundai-tucson-hybrid-pr-101-68a38aa37ded6.jpg?crop=0.682xw:0.576xh;0.129xw,0.338xh&resize=1200:*",
    pros: ["premium global design", "very comfortable cabin", "good adas package", "large boot space"],
    cons: ["high initial price", "fuel efficiency is average"],
    tags: ["luxury", "family", "highway"]
  },
  {
    slug: "tata-nexon-ev",
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 143,
    torqueNm: 215,
    mileageCity: 330,
    mileageHighway: 270,
    seatingCapacity: 5,
    bootLitres: 350,
    groundClearance: 190,
    priceMin: 1299000,
    priceMax: 1749000,
    monthlyService: 2100,
    insuranceYear1: 32000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.58,
    depRate5Yr: 0.41,
    imageUrl: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/149311/nexon-ev-right-front-three-quarter-5.jpeg?isig=0&q=80",
    pros: ["low running cost", "instant torque performance", "good city range", "5-star safety"],
    cons: ["charging network still growing", "highway range drops noticeably"],
    tags: ["ev", "city", "family"]
  },
  {
    slug: "mg-zs-ev",
    name: "MG ZS EV",
    brand: "MG",
    model: "ZS EV",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 174.33,
    torqueNm: 280,
    mileageCity: 390,
    mileageHighway: 320,
    seatingCapacity: 5,
    bootLitres: 448,
    groundClearance: 177,
    priceMin: 1898000,
    priceMax: 2498000,
    monthlyService: 2400,
    insuranceYear1: 41000,
    safetyRating: 5,
    depRate1Yr: 0.76,
    depRate3Yr: 0.56,
    depRate5Yr: 0.4,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/MG/ZS-EV/6873/1612778753498/front-left-side-47.jpg",
    pros: ["strong real-world range", "premium feature list", "quick acceleration", "comfortable family suv"],
    cons: ["higher upfront cost", "service footprint smaller than mass brands"],
    tags: ["ev", "luxury", "family"]
  },
  {
    slug: "mahindra-thar-4wd-diesel-at",
    name: "Mahindra Thar LX Hard Top Diesel AT 4WD",
    brand: "Mahindra",
    model: "Thar",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2184,
    powerBhp: 130,
    torqueNm: 300,
    mileageCity: 9,
    mileageHighway: 12,
    seatingCapacity: 4,
    bootLitres: 223,
    groundClearance: 226,
    priceMin: 1135000,
    priceMax: 1760000,
    monthlyService: 1500,
    insuranceYear1: 65000,
    safetyRating: 4,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/Thar-ROXX/8438/1755867262325/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Iconic design", "Exceptional off-road capability", "Improved interiors and features"],
    cons: ["Limited boot space", "Bumpy ride quality on highways", "Only 4-seater capacity"],
    tags: ["SUV", "4x4", "Off-road", "Lifestyle"]
  },
  {
    slug: "maruti-jimny-alpha-mt",
    name: "Maruti Suzuki Jimny Alpha MT",
    brand: "Maruti",
    model: "Jimny",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1462,
    powerBhp: 103,
    torqueNm: 134,
    mileageCity: 12,
    mileageHighway: 16,
    seatingCapacity: 4,
    bootLitres: 211,
    groundClearance: 210,
    priceMin: 1274000,
    priceMax: 1479000,
    monthlyService: 1200,
    insuranceYear1: 50000,
    safetyRating: 3,
    depRate1Yr: 0.85,
    depRate3Yr: 0.7,
    depRate5Yr: 0.55,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Jimny/6182/1762859095762/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Compact and easy to maneuver", "Solid off-road build quality", "Good brand resale value"],
    cons: ["Small boot space", "Limited rear legroom", "Relatively underpowered engine"],
    tags: ["SUV", "4x4", "Compact", "Lifestyle"]
  },
  {
    slug: "toyota-fortuner-2-8l-4x2-at-diesel",
    name: "Toyota Fortuner 2.8L 4x2 AT Diesel",
    brand: "Toyota",
    model: "Fortuner",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2755,
    powerBhp: 201,
    torqueNm: 500,
    mileageCity: 10,
    mileageHighway: 14,
    seatingCapacity: 7,
    bootLitres: 296,
    groundClearance: 225,
    priceMin: 3343000,
    priceMax: 5144000,
    monthlyService: 2000,
    insuranceYear1: 120000,
    safetyRating: 5,
    depRate1Yr: 0.85,
    depRate3Yr: 0.7,
    depRate5Yr: 0.55,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Toyota/Fortuner/10904/1755846017683/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Powerful diesel engine", "Excellent resale value", "Strong road presence"],
    cons: ["Expensive top-end variants", "Firm ride quality", "Lacks some modern tech features"],
    tags: ["SUV", "7-Seater", "Reliability", "Off-road"]
  },
  {
    slug: "maruti-grand-vitara-alpha-plus-hybrid-cvt",
    name: "Maruti Suzuki Grand Vitara Alpha+ Hybrid CVT",
    brand: "Maruti",
    model: "Grand Vitara",
    year: 2024,
    type: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineCC: 1490,
    powerBhp: 114,
    torqueNm: 141,
    mileageCity: 25,
    mileageHighway: 27,
    seatingCapacity: 5,
    bootLitres: 265,
    groundClearance: 210,
    priceMin: 1070000,
    priceMax: 1992000,
    monthlyService: 1000,
    insuranceYear1: 75000,
    safetyRating: 4,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Grand-Vitara/10501/1755776910397/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Exceptional fuel efficiency", "Smooth and silent drive", "Premium interiors and features"],
    cons: ["Small boot space due to battery", "Engine can be noisy under load", "High price for performance level"],
    tags: ["SUV", "Hybrid", "Fuel Efficient", "Nexa"]
  },
  {
    slug: "toyota-urban-cruiser-hyryder-v-hybrid",
    name: "Toyota Urban Cruiser Hyryder V Hybrid",
    brand: "Toyota",
    model: "Urban Cruiser Hyryder",
    year: 2024,
    type: "SUV",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineCC: 1490,
    powerBhp: 114,
    torqueNm: 141,
    mileageCity: 25,
    mileageHighway: 27,
    seatingCapacity: 5,
    bootLitres: 265,
    groundClearance: 210,
    priceMin: 1114000,
    priceMax: 2019000,
    monthlyService: 1200,
    insuranceYear1: 80000,
    safetyRating: 4,
    depRate1Yr: 0.82,
    depRate3Yr: 0.68,
    depRate5Yr: 0.52,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Toyota/Hyryder/12837/1776674323818/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Best-in-class fuel economy", "Toyota brand reliability", "Silent cabin operation"],
    cons: ["Limited boot capacity", "Interior plastics feel average", "Tight rear seat headroom"],
    tags: ["SUV", "Hybrid", "Fuel Efficient", "Reliable"]
  },
  {
    slug: "honda-elevate-zx-cvt",
    name: "Honda Elevate ZX CVT",
    brand: "Honda",
    model: "Elevate",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 119,
    torqueNm: 145,
    mileageCity: 13,
    mileageHighway: 16.92,
    seatingCapacity: 5,
    bootLitres: 458,
    groundClearance: 220,
    priceMin: 1170000,
    priceMax: 1667000,
    monthlyService: 6000,
    insuranceYear1: 55000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Honda/Elevate/12099/1758802336858/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Sleek compact SUV design", "Reliable 1.5L i-VTEC engine", "Advanced ADAS suite", "Spacious cabin and big boot"],
    cons: ["No diesel or hybrid engine options", "Mileage could be better compared to rivals"],
    tags: ["SUV", "Automatic", "Petrol", "Honda", "ADAS"]
  },
  {
    slug: "volkswagen-taigun-gt-plus-edge-1-5-tsi-dsg",
    name: "Volkswagen Taigun 1.5 TSI GT Plus Edge DSG",
    brand: "Volkswagen",
    model: "Taigun",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 148,
    torqueNm: 250,
    mileageCity: 14,
    mileageHighway: 19.01,
    seatingCapacity: 5,
    bootLitres: 385,
    groundClearance: 188,
    priceMin: 1100000,
    priceMax: 1930000,
    monthlyService: 8000,
    insuranceYear1: 65000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.68,
    depRate5Yr: 0.52,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/207718/taigun-facelift-exterior-left-front-three-quarter-9.webp?isig=0&q=80&q=80",
    pros: ["Fun to drive with powerful 1.5L TSI engine", "Solid build quality", "5-star Global NCAP safety rating", "Premium road presence"],
    cons: ["Rear seat is narrow for three adults", "Top variants are pricey", "Maintenance costs can be higher"],
    tags: ["SUV", "Automatic", "Petrol", "Volkswagen", "TSI", "DSG"]
  },
  {
    slug: "mg-astor-savvy-pro-sangria-turbo-at",
    name: "MG Astor Savvy Pro Sangria Turbo AT",
    brand: "MG",
    model: "Astor",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1349,
    powerBhp: 138,
    torqueNm: 220,
    mileageCity: 10,
    mileageHighway: 14.34,
    seatingCapacity: 5,
    bootLitres: 488,
    groundClearance: 205,
    priceMin: 998000,
    priceMax: 1828000,
    monthlyService: 7000,
    insuranceYear1: 60000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/MG/Astor/11413/1762752659543/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Loaded with tech and AI Assistant", "Premium Sangria Red interior", "Level 2 ADAS features", "Very comfortable ride quality"],
    cons: ["Turbo engine is less fuel-efficient", "Rear headroom is tight for tall passengers", "AI assistant can be occasionally gimmicky"],
    tags: ["SUV", "Automatic", "Petrol", "MG", "ADAS", "Turbo"]
  },
  {
    slug: "citroen-c3-aircross-max-5-seater-turbo-mt",
    name: "Citroen C3 Aircross Max 5-Seater Turbo MT",
    brand: "Citroen",
    model: "C3 Aircross",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1199,
    powerBhp: 109,
    torqueNm: 190,
    mileageCity: 14,
    mileageHighway: 18.5,
    seatingCapacity: 5,
    bootLitres: 444,
    groundClearance: 200,
    priceMin: 999000,
    priceMax: 1411000,
    monthlyService: 5000,
    insuranceYear1: 45000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.62,
    depRate5Yr: 0.48,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Citroen/Aircross/12973/1769597288445/front-left-side-47.jpg?tr=w-664",
    pros: ["Excellent ride comfort and suspension", "Spacious and flexible cabin", "Decent ground clearance for Indian roads", "Attractive and unique styling"],
    cons: ["Lacks many modern features like auto climate control", "Only one engine and transmission option", "Limited sales and service network"],
    tags: ["SUV", "Manual", "Petrol", "Citroen", "Turbo", "Comfort"]
  },
  {
    slug: "mahindra-scorpio-classic-s11-mt",
    name: "Mahindra Scorpio Classic S11 MT",
    brand: "Mahindra",
    model: "Scorpio Classic",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Manual",
    engineCC: 2184,
    powerBhp: 130,
    torqueNm: 300,
    mileageCity: 12,
    mileageHighway: 15,
    seatingCapacity: 7,
    bootLitres: 460,
    groundClearance: 209,
    priceMin: 1362000,
    priceMax: 1742000,
    monthlyService: 6500,
    insuranceYear1: 50000,
    safetyRating: 0,
    depRate1Yr: 0.85,
    depRate3Yr: 0.7,
    depRate5Yr: 0.55,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/128413/scorpio-classic-exterior-right-front-three-quarter.jpeg?isig=0",
    pros: ["Rugged and tough build quality", "Commanding road presence", "Proven and powerful mHawk diesel engine", "High resale value"],
    cons: ["Lacks modern safety tech (only 2 airbags)", "Ride quality can be bumpy on uneven roads", "Interior feels dated compared to Scorpio-N"],
    tags: ["SUV", "Manual", "Diesel", "Mahindra", "Rugged"]
  },
  {
    slug: "force-gurkha-2-6-diesel-3-door",
    name: "Force Gurkha 2.6 Diesel 3-Door",
    brand: "Force Motors",
    model: "Gurkha",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Manual",
    engineCC: 2596,
    powerBhp: 138,
    torqueNm: 320,
    mileageCity: 14,
    mileageHighway: 17,
    seatingCapacity: 4,
    bootLitres: 500,
    groundClearance: 233,
    priceMin: 1675000,
    priceMax: 1700000,
    monthlyService: 2500,
    insuranceYear1: 75000,
    safetyRating: 0,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/103517/force-motors-gurkha-new-left-front-three-quarter6.jpeg?isig=0&wm=0",
    pros: ["Excellent off-road capability", "Imposing road presence", "Standard snorkel for water wading"],
    cons: ["Basic interior quality", "Limited service network", "Lacks modern features"],
    tags: ["Off-roader", "4WD", "Diesel", "SUV"]
  },
  {
    slug: "tata-tiago-xza-plus-petrol",
    name: "Tata Tiago XZA+ Petrol",
    brand: "Tata Motors",
    model: "Tiago",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1199,
    powerBhp: 85,
    torqueNm: 113,
    mileageCity: 16,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 242,
    groundClearance: 170,
    priceMin: 770000,
    priceMax: 830000,
    monthlyService: 1500,
    insuranceYear1: 35000,
    safetyRating: 4,
    depRate1Yr: 0.82,
    depRate3Yr: 0.68,
    depRate5Yr: 0.55,
    imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/39345/tiago-exterior-right-front-three-quarter-34.png?isig=0&q=80",
    pros: ["4-star GNCAP safety rating", "Robust build quality", "Value for money features"],
    cons: ["3-cylinder engine vibrations", "Rear seat space is tight for three", "AMT is not as smooth as modern automatics"],
    tags: ["Safe", "Compact", "AMT", "Hatchback"]
  },
  {
    slug: "tata-tigor-xza-plus-petrol",
    name: "Tata Tigor XZA+ Petrol",
    brand: "Tata Motors",
    model: "Tigor",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1199,
    powerBhp: 85,
    torqueNm: 113,
    mileageCity: 16,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 419,
    groundClearance: 170,
    priceMin: 840000,
    priceMax: 895000,
    monthlyService: 1800,
    insuranceYear1: 38000,
    safetyRating: 4,
    depRate1Yr: 0.8,
    depRate3Yr: 0.65,
    depRate5Yr: 0.52,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Tata/Tigor/10670/1767964333729/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Spacious 419L boot", "4-star safety rating", "Good ride quality"],
    cons: ["Engine noise at high RPMs", "Infotainment system can be laggy", "Dated interior design elements"],
    tags: ["Sedan", "Safe", "Family Car", "AMT"]
  },
  {
    slug: "hyundai-grand-i10-nios-asta-petrol",
    name: "Hyundai Grand i10 Nios Asta Petrol",
    brand: "Hyundai",
    model: "Grand i10 Nios",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1197,
    powerBhp: 82,
    torqueNm: 114,
    mileageCity: 15,
    mileageHighway: 18,
    seatingCapacity: 5,
    bootLitres: 260,
    groundClearance: 165,
    priceMin: 795000,
    priceMax: 856000,
    monthlyService: 2000,
    insuranceYear1: 32000,
    safetyRating: 2,
    depRate1Yr: 0.85,
    depRate3Yr: 0.7,
    depRate5Yr: 0.55,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Grand-i10-Nios/10088/1762430432997/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Smooth 4-cylinder engine", "Feature-rich cabin", "Excellent city maneuverability"],
    cons: ["Low safety rating", "Rear seat is best for two adults", "Lacks some premium features found in i20"],
    tags: ["City Car", "Smooth", "Feature-rich", "Hatchback"]
  },
  {
    slug: "hyundai-aura-sx-plus-petrol",
    name: "Hyundai Aura SX Plus Petrol",
    brand: "Hyundai",
    model: "Aura",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 82,
    torqueNm: 114,
    mileageCity: 15,
    mileageHighway: 17,
    seatingCapacity: 5,
    bootLitres: 402,
    groundClearance: 165,
    priceMin: 875000,
    priceMax: 890000,
    monthlyService: 2200,
    insuranceYear1: 36000,
    safetyRating: 2,
    depRate1Yr: 0.83,
    depRate3Yr: 0.68,
    depRate5Yr: 0.53,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Hyundai/Aura/10125/1762429751468/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: ["Premium interior feel", "Reliable after-sales service", "Practical boot space"],
    cons: ["Low safety rating", "Steering is very light at high speeds", "Design can be polarising"],
    tags: ["Sedan", "AMT", "Hyundai", "Practical"]
  },
  {
    slug: "maruti-dzire-zxi-plus-amt-2024",
    name: "Maruti Suzuki Dzire ZXI Plus AMT",
    brand: "Maruti Suzuki",
    model: "Dzire",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 80,
    torqueNm: 111.7,
    mileageCity: 18,
    mileageHighway: 25.71,
    seatingCapacity: 5,
    bootLitres: 382,
    groundClearance: 163,
    priceMin: 657000,
    priceMax: 1014000,
    monthlyService: 1500,
    insuranceYear1: 35000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.68,
    depRate5Yr: 0.52,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Maruti/Dzire/12186/1771935643542/front-left-side-47.jpg",
    pros: [
      "Excellent Fuel Efficiency",
      "First Maruti with 5-star Bharat NCAP rating",
      "Modern feature set including sunroof"
    ],
    cons: [
      "AMT shift can feel jerky under hard acceleration",
      "Cabin width is tight for three adults in the rear"
    ],
    tags: ["Sedan", "Fuel Efficient", "Family Car", "AMT", "Safe"]
  },
  {
    slug: "maruti-wagon-r-zxi-plus-12-amt-2024",
    name: "Maruti Suzuki Wagon R ZXI Plus 1.2 AMT",
    brand: "Maruti Suzuki",
    model: "Wagon R",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 89,
    torqueNm: 113,
    mileageCity: 17,
    mileageHighway: 24.43,
    seatingCapacity: 5,
    bootLitres: 341,
    groundClearance: 165,
    priceMin: 499000,
    priceMax: 720000,
    monthlyService: 1200,
    insuranceYear1: 30000,
    safetyRating: 1,
    depRate1Yr: 0.85,
    depRate3Yr: 0.70,
    depRate5Yr: 0.55,
    imageUrl: "https://imgd.aeplcdn.com/1056x594/n/7lto5ua_1560265.jpg?q=80",
    pros: [
      "Extremely spacious and airy cabin",
      "Tall-boy design makes ingress/egress easy",
      "Peppy 1.2L engine performance"
    ],
    cons: [
      "Weak safety structure (1-star GNCAP)",
      "High-speed stability and NVH levels are average"
    ],
    tags: ["Hatchback", "City Car", "Practical", "Tall Boy", "AMT"]
  },
  {
    slug: "maruti-alto-k10-vxi-plus-2024",
    name: "Maruti Suzuki Alto K10 VXI Plus",
    brand: "Maruti Suzuki",
    model: "Alto K10",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 998,
    powerBhp: 66,
    torqueNm: 89,
    mileageCity: 18,
    mileageHighway: 24.39,
    seatingCapacity: 5,
    bootLitres: 214,
    groundClearance: 160,
    priceMin: 399000,
    priceMax: 535000,
    monthlyService: 1000,
    insuranceYear1: 20000,
    safetyRating: 2,
    depRate1Yr: 0.82,
    depRate3Yr: 0.65,
    depRate5Yr: 0.50,
    imageUrl: "https://www.autovista.in/assets/img/new_cars_colour_variants/Alto_K10-brown.png",
    pros: [
      "Most affordable and reliable entry-level car",
      "Perfect dimensions for tight city traffic",
      "Strong resale value"
    ],
    cons: [
      "Very basic interior quality",
      "Limited rear legroom and boot space"
    ],
    tags: ["Hatchback", "Entry Level", "Budget", "City Car", "Reliable"]
  },
  {
    slug: "maruti-celerio-zxi-plus-amt-2024",
    name: "Maruti Suzuki Celerio ZXI Plus AMT",
    brand: "Maruti Suzuki",
    model: "Celerio",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 998,
    powerBhp: 66,
    torqueNm: 89,
    mileageCity: 19,
    mileageHighway: 26.68,
    seatingCapacity: 5,
    bootLitres: 313,
    groundClearance: 170,
    priceMin: 537000,
    priceMax: 700000,
    monthlyService: 1200,
    insuranceYear1: 25000,
    safetyRating: 0,
    depRate1Yr: 0.80,
    depRate3Yr: 0.65,
    depRate5Yr: 0.50,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Maruti/Celerio/10355/1762857367030/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: [
      "Class-leading ARAI mileage",
      "Contemporary design and light controls",
      "Good boot space for its size"
    ],
    cons: [
      "Lacks a premium feel compared to rivals",
      "Safety rating is not impressive"
    ],
    tags: ["Hatchback", "Fuel Efficient", "City Car", "AMT", "Practical"]
  },
  {
    slug: "renault-kwid-climber-amt-2024",
    name: "Renault Kwid Climber AMT",
    brand: "Renault",
    model: "Kwid",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 999,
    powerBhp: 67,
    torqueNm: 91,
    mileageCity: 16,
    mileageHighway: 22.3,
    seatingCapacity: 5,
    bootLitres: 279,
    groundClearance: 184,
    priceMin: 470000,
    priceMax: 630000,
    monthlyService: 1500,
    insuranceYear1: 25000,
    safetyRating: 1,
    depRate1Yr: 0.78,
    depRate3Yr: 0.62,
    depRate5Yr: 0.48,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Renault/KWID/12956/1758713208477/front-left-side-47.jpg?imwidth=420&impolicy=resize",
    pros: [
      "Aggressive SUV-like styling",
      "High ground clearance for Indian roads",
      "Touchscreen and modern tech features"
    ],
    cons: [
      "Three-cylinder engine is vocal and vibrates",
      "Resale value is lower than Maruti competitors"
    ],
    tags: ["Hatchback", "Crossover", "Stylish", "AMT", "High Clearance"]
  },
  {
    slug: "renault-kiger-rxz-turbo-cvt",
    name: "Renault Kiger RXZ Turbo CVT",
    brand: "Renault",
    model: "Kiger",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 999,
    powerBhp: 99,
    torqueNm: 152,
    mileageCity: 14,
    mileageHighway: 18.24,
    seatingCapacity: 5,
    bootLitres: 405,
    groundClearance: 205,
    priceMin: 600000,
    priceMax: 1123000,
    monthlyService: 1800,
    insuranceYear1: 42000,
    safetyRating: 4,
    depRate1Yr: 0.78,
    depRate3Yr: 0.62,
    depRate5Yr: 0.48,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/208550/kiger-exterior-right-front-three-quarter-30.png?isig=0&q=80&q=80",
    pros: ["Spacious cabin and big boot", "Stylish design", "Value for money"],
    cons: ["Poor cabin insulation", "No sunroof", "Sluggish in Eco mode"],
    tags: ["SUV", "City", "Stylish", "Automatic"]
  },
  {
    slug: "renault-triber-rxz-amt",
    name: "Renault Triber RXZ AMT",
    brand: "Renault",
    model: "Triber",
    year: 2024,
    type: "MUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 999,
    powerBhp: 71,
    torqueNm: 96,
    mileageCity: 12,
    mileageHighway: 18.2,
    seatingCapacity: 7,
    bootLitres: 84,
    groundClearance: 182,
    priceMin: 600000,
    priceMax: 875000,
    monthlyService: 1500,
    insuranceYear1: 38000,
    safetyRating: 2,
    depRate1Yr: 0.76,
    depRate3Yr: 0.60,
    depRate5Yr: 0.45,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/207308/triber-exterior-right-front-three-quarter.jpeg?isig=0&wm=0",
    pros: ["Modular seating", "Spacious for its size", "Affordable 7-seater"],
    cons: ["Engine feels underpowered", "Average safety rating", "AMT is basic"],
    tags: ["MUV", "Family", "7-Seater", "Budget"]
  },
  {
    slug: "nissan-magnite-turbo-cvt",
    name: "Nissan Magnite Turbo CVT",
    brand: "Nissan",
    model: "Magnite",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 999,
    powerBhp: 99,
    torqueNm: 152,
    mileageCity: 13,
    mileageHighway: 17.9,
    seatingCapacity: 5,
    bootLitres: 336,
    groundClearance: 205,
    priceMin: 600000,
    priceMax: 1096000,
    monthlyService: 1600,
    insuranceYear1: 40000,
    safetyRating: 4,
    depRate1Yr: 0.79,
    depRate3Yr: 0.63,
    depRate5Yr: 0.49,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/173325/magnite-exterior-right-front-three-quarter-27.png?isig=0&q=80",
    pros: ["Attractive pricing", "Good safety score", "Smooth CVT"],
    cons: ["Small service network", "Interior fit and finish", "No diesel option"],
    tags: ["SUV", "Value", "Safe", "Automatic"]
  },
  {
    slug: "byd-atto-3",
    name: "BYD Atto 3 Extended Range",
    brand: "BYD",
    model: "Atto 3",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 201,
    torqueNm: 310,
    mileageCity: 480,
    mileageHighway: 400,
    seatingCapacity: 5,
    bootLitres: 440,
    groundClearance: 175,
    priceMin: 2499000,
    priceMax: 3399000,
    monthlyService: 2500,
    insuranceYear1: 95000,
    safetyRating: 5,
    depRate1Yr: 0.75,
    depRate3Yr: 0.55,
    depRate5Yr: 0.40,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/130183/atto-3-exterior-right-front-three-quarter-102.jpeg?isig=0&q=80",
    pros: ["Excellent range", "Premium interiors", "Quick acceleration"],
    cons: ["High price", "Relatively new brand", "Polarising interior bits"],
    tags: ["Electric", "EV", "Luxury", "Performance"]
  },
  {
    slug: "tata-tiago-ev-long-range",
    name: "Tata Tiago EV Long Range",
    brand: "Tata",
    model: "Tiago EV",
    year: 2024,
    type: "Hatchback",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 74,
    torqueNm: 114,
    mileageCity: 280,
    mileageHighway: 220,
    seatingCapacity: 5,
    bootLitres: 240,
    groundClearance: 166,
    priceMin: 870000,
    priceMax: 1190000,
    monthlyService: 1200,
    insuranceYear1: 45000,
    safetyRating: 4,
    depRate1Yr: 0.78,
    depRate3Yr: 0.58,
    depRate5Yr: 0.42,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/40453/tiago-ev-exterior-right-front-three-quarter-15.png?isig=0&q=80&q=80",
    pros: ["Low running cost", "Compact for city", "Smooth drive"],
    cons: ["Limited highway range", "Rear space is tight", "Charging takes time"],
    tags: ["Electric", "EV", "City", "Budget"]
  },
  {
    slug: "mahindra-xuv400",
    name: "Mahindra XUV400",
    brand: "Mahindra",
    model: "XUV400",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 148,
    torqueNm: 310,
    mileageCity: 400,
    mileageHighway: 330,
    seatingCapacity: 5,
    bootLitres: 378,
    groundClearance: 200,
    priceMin: 1549000,
    priceMax: 1939000,
    monthlyService: 1800,
    insuranceYear1: 70000,
    safetyRating: 5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.57,
    depRate5Yr: 0.41,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/45278/xuv400-exterior-right-front-three-quarter-8.png?isig=0&q=80&q=80",
    pros: ["Fast performance", "Good cabin space", "BNCAP 5-star"],
    cons: ["Interior feels dated", "Missing some tech", "Rear seat comfort"],
    tags: ["Electric", "EV", "Performance", "SUV"]
  },
  {
    slug: "toyota-hilux",
    name: "Toyota Hilux",
    brand: "Toyota",
    model: "Hilux",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2755,
    powerBhp: 201,
    torqueNm: 500,
    mileageCity: 8,
    mileageHighway: 11,
    seatingCapacity: 5,
    bootLitres: 435,
    groundClearance: 279,
    priceMin: 3040000,
    priceMax: 3790000,
    monthlyService: 3500,
    insuranceYear1: 85000,
    safetyRating: 3,
    depRate1Yr: 0.85,
    depRate3Yr: 0.72,
    depRate5Yr: 0.60,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/165765/toyota-hilux-right-front-three-quarter17.jpeg?isig=0&wm=1&q=80",
    pros: ["Go-anywhere ability", "Bulletproof reliability", "Massive road presence"],
    cons: ["Very long for city", "Bumpy ride when empty", "Expensive pickup"],
    tags: ["Lifestyle", "Off-road", "Reliability", "Diesel"]
  },
  {
    slug: "toyota-camry-hybrid",
    name: "Toyota Camry Hybrid",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    type: "Sedan",
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineCC: 2487,
    powerBhp: 215,
    torqueNm: 221,
    mileageCity: 20,
    mileageHighway: 25,
    seatingCapacity: 5,
    bootLitres: 524,
    groundClearance: 160,
    priceMin: 4748000,
    priceMax: 4800000,
    monthlyService: 4500,
    insuranceYear1: 110000,
    safetyRating: 5,
    depRate1Yr: 0.80,
    depRate3Yr: 0.65,
    depRate5Yr: 0.50,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/192443/camry-exterior-right-front-three-quarter-15.png?isig=0&q=80&q=80",
    pros: ["Superb refinement", "Great fuel efficiency", "Chauffeur comfort"],
    cons: ["Lacks sporty feel", "Low ground clearance", "Expensive premium sedan"],
    tags: ["Luxury", "Hybrid", "Comfort", "Sedan"]
  },
  {
    slug: "skoda-superb-tsi",
    name: "Skoda Superb TSI",
    brand: "Skoda",
    model: "Superb",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1984,
    powerBhp: 187,
    torqueNm: 320,
    mileageCity: 12,
    mileageHighway: 17,
    seatingCapacity: 5,
    bootLitres: 625,
    groundClearance: 156,
    priceMin: 5400000,
    priceMax: 5500000,
    monthlyService: 5000,
    insuranceYear1: 125000,
    safetyRating: 5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.58,
    depRate5Yr: 0.42,
    imageUrl: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/158937/superb-exterior-right-front-three-quarter-6.jpeg?isig=0&q=80",
    pros: ["Classy interiors", "Huge boot space", "Punchy TSI engine"],
    cons: ["High maintenance cost", "Low ground clearance", "Limited availability"],
    tags: ["Luxury", "Sedan", "Performance", "Spacious"]
  },
  {
    slug: "jeep-compass-diesel",
    name: "Jeep Compass Diesel",
    brand: "Jeep",
    model: "Compass",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168,
    torqueNm: 350,
    mileageCity: 11,
    mileageHighway: 16,
    seatingCapacity: 5,
    bootLitres: 438,
    groundClearance: 178,
    priceMin: 1799000,
    priceMax: 3070000,
    monthlyService: 4800,
    insuranceYear1: 80000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.60,
    depRate5Yr: 0.45,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/47051/compass-exterior-left-front-three-quarter-23.jpeg?isig=0&q=80&q=80",
    pros: ["Premium build quality", "Great highway stability", "Strong diesel punch"],
    cons: ["Automatic is a bit slow", "Pricey top variants", "Rear seat width"],
    tags: ["SUV", "Luxury", "Safe", "Highway"]
  }
];

async function main() {
  await prisma.savedCar.deleteMany();
  await prisma.car.deleteMany();

  await prisma.car.createMany({
    data: cars
  });

  console.log(`Seeded ${cars.length} cars`);
}

main()
  .catch((error) => {
    console.error("Seeding failed:", error);
    throw error;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
