import { Prisma, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cars: Prisma.CarCreateManyInput[] = [
  {
    slug: "maruti-swift",
    name: "Maruti Swift",
    brand: "Maruti",
    model: "Swift",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1197,
    powerBhp: 80.46,
    torqueNm: 111.7,
    mileageCity: 20.5,
    mileageHighway: 24.8,
    seatingCapacity: 5,
    bootLitres: 265,
    groundClearance: 163,
    priceMin: 649000,
    priceMax: 964000,
    monthlyService: 2400,
    insuranceYear1: 21000,
    safetyRating: 3,
    depRate1Yr: 0.84,
    depRate3Yr: 0.68,
    depRate5Yr: 0.53,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj_JYNnZNYoLinkR8t5_8beeuImeDboKQ-sQ&s",
    pros: ["great fuel economy", "easy city driving", "low maintenance cost", "wide service network"],
    cons: ["rear seat comfort is average", "basic cabin quality", "highway stability could improve"],
    tags: ["city", "budget", "family"]
  },
  {
    slug: "hyundai-i20",
    name: "Hyundai i20",
    brand: "Hyundai",
    model: "i20",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 86.76,
    torqueNm: 114.7,
    mileageCity: 16.8,
    mileageHighway: 20.2,
    seatingCapacity: 5,
    bootLitres: 311,
    groundClearance: 170,
    priceMin: 704000,
    priceMax: 1174000,
    monthlyService: 2700,
    insuranceYear1: 24000,
    safetyRating: 3,
    depRate1Yr: 0.82,
    depRate3Yr: 0.66,
    depRate5Yr: 0.5,
    imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/158139/i20-n-line-exterior-right-front-three-quarter-16.png?isig=0&q=80",
    pros: ["premium interiors", "feature loaded variants", "refined petrol engine", "good boot space"],
    cons: ["not the most fuel efficient", "rear headroom is tight"],
    tags: ["city", "sporty", "family"]
  },
  {
    slug: "tata-altroz",
    name: "Tata Altroz",
    brand: "Tata",
    model: "Altroz",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1199,
    powerBhp: 86.79,
    torqueNm: 115,
    mileageCity: 17.2,
    mileageHighway: 21,
    seatingCapacity: 5,
    bootLitres: 345,
    groundClearance: 165,
    priceMin: 665000,
    priceMax: 1109000,
    monthlyService: 2600,
    insuranceYear1: 23000,
    safetyRating: 5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.48,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Tata/Altroz/12614/1770888054138/front-left-side-47.jpg",
    pros: ["5-star safety rating", "solid build quality", "large boot for hatchback", "comfortable ride"],
    cons: ["engine feels less punchy", "service quality varies by city"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "maruti-baleno",
    name: "Maruti Baleno",
    brand: "Maruti",
    model: "Baleno",
    year: 2024,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1197,
    powerBhp: 88.5,
    torqueNm: 113,
    mileageCity: 20.1,
    mileageHighway: 23.7,
    seatingCapacity: 5,
    bootLitres: 318,
    groundClearance: 170,
    priceMin: 666000,
    priceMax: 988000,
    monthlyService: 2350,
    insuranceYear1: 21500,
    safetyRating: 3,
    depRate1Yr: 0.84,
    depRate3Yr: 0.69,
    depRate5Yr: 0.54,
    imageUrl: "https://imgd.aeplcdn.com/642x336/n/cw/ec/102663/baleno-exterior-right-front-three-quarter-69.png?isig=0&q=80",
    pros: ["excellent mileage", "spacious rear seat", "smooth automatic option", "low running costs"],
    cons: ["safety rating could be better", "steering feedback is light"],
    tags: ["city", "family", "budget"]
  },
  {
    slug: "honda-jazz",
    name: "Honda Jazz",
    brand: "Honda",
    model: "Jazz",
    year: 2023,
    type: "Hatchback",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1199,
    powerBhp: 88.5,
    torqueNm: 110,
    mileageCity: 16.2,
    mileageHighway: 19.8,
    seatingCapacity: 5,
    bootLitres: 354,
    groundClearance: 165,
    priceMin: 821000,
    priceMax: 989000,
    monthlyService: 2500,
    insuranceYear1: 22000,
    safetyRating: 4,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/Jazz/6489/1677825341880/front-left-side-47.jpg",
    pros: ["very practical cabin", "magic seats flexibility", "reliable ivtec engine"],
    cons: ["older design", "limited variant choices", "discontinued in many markets"],
    tags: ["family", "city", "spacious"]
  },
  {
    slug: "honda-city",
    name: "Honda City",
    brand: "Honda",
    model: "City",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 119.35,
    torqueNm: 145,
    mileageCity: 15.5,
    mileageHighway: 18.9,
    seatingCapacity: 5,
    bootLitres: 506,
    groundClearance: 165,
    priceMin: 1190000,
    priceMax: 1625000,
    monthlyService: 3000,
    insuranceYear1: 32000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.64,
    depRate5Yr: 0.49,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/City/12093/1755764990493/front-left-side-47.jpg",
    pros: ["premium cabin feel", "class-leading rear space", "refined engine", "big boot"],
    cons: ["lower variants miss features", "ground clearance is moderate"],
    tags: ["family", "highway", "spacious"]
  },
  {
    slug: "maruti-ciaz",
    name: "Maruti Ciaz",
    brand: "Maruti",
    model: "Ciaz",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1462,
    powerBhp: 103.25,
    torqueNm: 138,
    mileageCity: 17.4,
    mileageHighway: 21.1,
    seatingCapacity: 5,
    bootLitres: 510,
    groundClearance: 170,
    priceMin: 930000,
    priceMax: 1229000,
    monthlyService: 2500,
    insuranceYear1: 26000,
    safetyRating: 4,
    depRate1Yr: 0.83,
    depRate3Yr: 0.67,
    depRate5Yr: 0.52,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/48542/ciaz-exterior-right-side-view.jpeg?q=80&q=80",
    pros: ["great mileage for sedan", "comfortable rear seat", "low upkeep cost"],
    cons: ["interior design feels dated", "limited engine options"],
    tags: ["family", "highway", "budget"]
  },
  {
    slug: "hyundai-verna",
    name: "Hyundai Verna",
    brand: "Hyundai",
    model: "Verna",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.57,
    torqueNm: 253,
    mileageCity: 14.1,
    mileageHighway: 18.3,
    seatingCapacity: 5,
    bootLitres: 528,
    groundClearance: 165,
    priceMin: 1100000,
    priceMax: 1787000,
    monthlyService: 3200,
    insuranceYear1: 34000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.47,
    imageUrl: "https://imgd.aeplcdn.com/642x336/n/cw/ec/41197/hyundai-verna-right-front-three-quarter7.jpeg?q=80",
    pros: ["powerful turbo engine", "segment-best features", "large boot space", "good safety package"],
    cons: ["design may not suit everyone", "rear headroom is average"],
    tags: ["sporty", "highway", "family"]
  },
  {
    slug: "skoda-slavia",
    name: "Skoda Slavia",
    brand: "Skoda",
    model: "Slavia",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.51,
    torqueNm: 250,
    mileageCity: 14.6,
    mileageHighway: 19.2,
    seatingCapacity: 5,
    bootLitres: 521,
    groundClearance: 179,
    priceMin: 1069000,
    priceMax: 1869000,
    monthlyService: 3500,
    insuranceYear1: 36000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Skoda/Slavia/11810/1762938173534/front-left-side-47.jpg",
    pros: ["strong performance", "european driving dynamics", "huge boot capacity"],
    cons: ["maintenance cost is higher", "rear seat width is average"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "volkswagen-virtus",
    name: "VW Virtus",
    brand: "Volkswagen",
    model: "Virtus",
    year: 2024,
    type: "Sedan",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.5,
    torqueNm: 250,
    mileageCity: 14.4,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 521,
    groundClearance: 179,
    priceMin: 1156000,
    priceMax: 1939000,
    monthlyService: 3600,
    insuranceYear1: 37000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://imgd.aeplcdn.com/642x361/n/cw/ec/184551/volkswagen-virtus-right-front-three-quarter0.jpeg?isig=0&q=75",
    pros: ["great high-speed stability", "solid build quality", "powerful gt variant", "large boot"],
    cons: ["service network is smaller", "top variants are expensive"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "tata-nexon",
    name: "Tata Nexon",
    brand: "Tata",
    model: "Nexon",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1199,
    powerBhp: 118.27,
    torqueNm: 170,
    mileageCity: 16.1,
    mileageHighway: 20.2,
    seatingCapacity: 5,
    bootLitres: 382,
    groundClearance: 208,
    priceMin: 799000,
    priceMax: 1499000,
    monthlyService: 2800,
    insuranceYear1: 26000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.65,
    depRate5Yr: 0.49,
    imageUrl: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/149311/nexon-ev-right-front-three-quarter-5.jpeg?isig=0&q=80",
    pros: ["5-star safety", "high ground clearance", "feature-rich trims", "strong road presence"],
    cons: ["cabin ergonomics need improvement", "after-sales inconsistency"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "maruti-brezza",
    name: "Maruti Brezza",
    brand: "Maruti",
    model: "Brezza",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1462,
    powerBhp: 101.65,
    torqueNm: 136.8,
    mileageCity: 17.2,
    mileageHighway: 20.1,
    seatingCapacity: 5,
    bootLitres: 328,
    groundClearance: 198,
    priceMin: 834000,
    priceMax: 1398000,
    monthlyService: 2500,
    insuranceYear1: 25000,
    safetyRating: 4,
    depRate1Yr: 0.84,
    depRate3Yr: 0.68,
    depRate5Yr: 0.54,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-zHg3VfFFCOh0fwENPRGUKwXhIi8nt4pSWw&s",
    pros: ["reliable ownership", "good mileage", "wide service reach"],
    cons: ["boot space is average", "interior quality is decent not premium"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "hyundai-venue",
    name: "Hyundai Venue",
    brand: "Hyundai",
    model: "Venue",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 998,
    powerBhp: 118.41,
    torqueNm: 172,
    mileageCity: 15.8,
    mileageHighway: 19.4,
    seatingCapacity: 5,
    bootLitres: 350,
    groundClearance: 190,
    priceMin: 794000,
    priceMax: 1362000,
    monthlyService: 2750,
    insuranceYear1: 25500,
    safetyRating: 4,
    depRate1Yr: 0.82,
    depRate3Yr: 0.65,
    depRate5Yr: 0.5,
    imageUrl: "https://www.carandbike.com/_next/image?url=https%3A%2F%2Fimages.carandbike.com%2Fcar-images%2Fgallery%2Fhyundai%2Fvenue%2Fexterior%2Fhyundai_venue_sideview.jpg%3Fv%3D1763533769&w=640&q=90",
    pros: ["compact and easy to park", "feature-packed cabin", "refined turbo engine"],
    cons: ["rear space is tight for three", "ride can feel firm"],
    tags: ["city", "sporty", "budget"]
  },
  {
    slug: "kia-sonet",
    name: "Kia Sonet",
    brand: "Kia",
    model: "Sonet",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 998,
    powerBhp: 118.36,
    torqueNm: 172,
    mileageCity: 15.6,
    mileageHighway: 19,
    seatingCapacity: 5,
    bootLitres: 385,
    groundClearance: 205,
    priceMin: 799000,
    priceMax: 1550000,
    monthlyService: 2900,
    insuranceYear1: 27000,
    safetyRating: 3.5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.48,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/174423/sonet-exterior-left-front-three-quarter.jpeg?isig=0&q=80&q=80",
    pros: ["premium cabin design", "many transmission options", "good feature list", "strong urban appeal"],
    cons: ["rear seat is not the widest", "suspension is on firmer side"],
    tags: ["city", "sporty", "family"]
  },
  {
    slug: "mahindra-xuv300",
    name: "Mahindra XUV300",
    brand: "Mahindra",
    model: "XUV300",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Manual",
    engineCC: 1197,
    powerBhp: 108.59,
    torqueNm: 200,
    mileageCity: 15,
    mileageHighway: 18.1,
    seatingCapacity: 5,
    bootLitres: 257,
    groundClearance: 180,
    priceMin: 799000,
    priceMax: 1449000,
    monthlyService: 2950,
    insuranceYear1: 26500,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.62,
    depRate5Yr: 0.46,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Mahindra/XUV300/6794/1701855582193/front-left-side-47.jpg",
    pros: ["excellent safety score", "strong turbo torque", "stable ride quality"],
    cons: ["small boot space", "cabin feels dated"],
    tags: ["family", "city", "budget"]
  },
  {
    slug: "hyundai-creta",
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1497,
    powerBhp: 113.18,
    torqueNm: 143.8,
    mileageCity: 15.3,
    mileageHighway: 18.4,
    seatingCapacity: 5,
    bootLitres: 433,
    groundClearance: 190,
    priceMin: 1100000,
    priceMax: 2000000,
    monthlyService: 3300,
    insuranceYear1: 36000,
    safetyRating: 3.5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.66,
    depRate5Yr: 0.51,
    imageUrl: "https://media.zigcdn.com/media/model/2026/Feb/front-1-4-left-1724564915_600x400.jpg",
    pros: ["segment benchmark features", "comfortable ride", "strong resale value", "good cabin quality"],
    cons: ["base variants miss features", "safety rating could be better"],
    tags: ["family", "city", "highway"]
  },
  {
    slug: "kia-seltos",
    name: "Kia Seltos",
    brand: "Kia",
    model: "Seltos",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.81,
    torqueNm: 253,
    mileageCity: 14.8,
    mileageHighway: 18.2,
    seatingCapacity: 5,
    bootLitres: 433,
    groundClearance: 190,
    priceMin: 1090000,
    priceMax: 2045000,
    monthlyService: 3400,
    insuranceYear1: 37000,
    safetyRating: 3.5,
    depRate1Yr: 0.81,
    depRate3Yr: 0.64,
    depRate5Yr: 0.49,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Kia/Seltos/7111/1678424780936/front-left-side-47.jpg",
    pros: ["powerful turbo option", "premium interiors", "advanced adas features", "great infotainment"],
    cons: ["ride quality is a bit stiff", "higher variants are pricey"],
    tags: ["sporty", "family", "highway"]
  },
  {
    slug: "tata-harrier",
    name: "Tata Harrier",
    brand: "Tata",
    model: "Harrier",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168.0,
    torqueNm: 350,
    mileageCity: 13.4,
    mileageHighway: 16.8,
    seatingCapacity: 5,
    bootLitres: 445,
    groundClearance: 205,
    priceMin: 1549000,
    priceMax: 2664000,
    monthlyService: 4200,
    insuranceYear1: 43000,
    safetyRating: 5,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsDXM_oJlzTY63PV8K5ED88I0Liczr0Pvthg&s",
    pros: ["solid road presence", "5-star safety", "strong diesel performance", "comfortable highway manners"],
    cons: ["city drivability can feel bulky", "higher maintenance than compact suvs"],
    tags: ["highway", "family", "spacious"]
  },
  {
    slug: "mg-hector",
    name: "MG Hector",
    brand: "MG",
    model: "Hector",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1451,
    powerBhp: 141.04,
    torqueNm: 250,
    mileageCity: 12.8,
    mileageHighway: 15.7,
    seatingCapacity: 5,
    bootLitres: 587,
    groundClearance: 192,
    priceMin: 1399000,
    priceMax: 2259000,
    monthlyService: 4100,
    insuranceYear1: 42000,
    safetyRating: 3.5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.59,
    depRate5Yr: 0.43,
    imageUrl: "https://imgd.aeplcdn.com/664x374/n/cw/ec/130583/hector-exterior-right-front-three-quarter-73.jpeg?isig=0&q=80",
    pros: ["massive cabin space", "huge touchscreen", "comfortable seats", "good highway cruiser"],
    cons: ["fuel efficiency is low", "soft handling around corners"],
    tags: ["spacious", "family", "highway"]
  },
  {
    slug: "mahindra-xuv700",
    name: "Mahindra XUV700",
    brand: "Mahindra",
    model: "XUV700",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2198,
    powerBhp: 182.38,
    torqueNm: 450,
    mileageCity: 13.2,
    mileageHighway: 16.6,
    seatingCapacity: 7,
    bootLitres: 240,
    groundClearance: 200,
    priceMin: 1399000,
    priceMax: 2649000,
    monthlyService: 4300,
    insuranceYear1: 45000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.47,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/630x420/Mahindra/XUV700/10794/1762509966753/front-left-side-47.jpg?tr=w-664",
    pros: ["strong performance options", "adas and tech loaded", "5-star safety", "available 7-seater"],
    cons: ["long waiting periods in some cities", "third row is best for kids"],
    tags: ["family", "highway", "spacious"]
  },
  {
    slug: "toyota-innova-crysta",
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2024,
    type: "MUV",
    fuelType: "Diesel",
    transmission: "Manual",
    engineCC: 2393,
    powerBhp: 147.51,
    torqueNm: 343,
    mileageCity: 11.4,
    mileageHighway: 14.3,
    seatingCapacity: 7,
    bootLitres: 300,
    groundClearance: 176,
    priceMin: 1999000,
    priceMax: 2699000,
    monthlyService: 4700,
    insuranceYear1: 49000,
    safetyRating: 5,
    depRate1Yr: 0.82,
    depRate3Yr: 0.69,
    depRate5Yr: 0.56,
    imageUrl: "https://mda.spinny.com/sp-file-system/public/2025-04-03/b895649aac3e40a0b692627684c0163a/raw/file.JPG",
    pros: ["legendary reliability", "very comfortable second row", "excellent resale value", "great long-distance comfort"],
    cons: ["pricey for features offered", "diesel only now"],
    tags: ["family", "spacious", "highway"]
  },
  {
    slug: "kia-carens",
    name: "Kia Carens",
    brand: "Kia",
    model: "Carens",
    year: 2024,
    type: "MUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1482,
    powerBhp: 157.81,
    torqueNm: 253,
    mileageCity: 14.2,
    mileageHighway: 17.5,
    seatingCapacity: 7,
    bootLitres: 216,
    groundClearance: 195,
    priceMin: 1052000,
    priceMax: 1952000,
    monthlyService: 3400,
    insuranceYear1: 35000,
    safetyRating: 3,
    depRate1Yr: 0.8,
    depRate3Yr: 0.63,
    depRate5Yr: 0.48,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuZ7bSPNjOan8_OeTbElOjK_1YD5m9ZpBrgQ&s",
    pros: ["great family practicality", "comfortable three rows", "feature rich cabin", "multiple powertrains"],
    cons: ["third-row boot space is limited", "not as rugged as suvs"],
    tags: ["family", "spacious", "city"]
  },
  {
    slug: "maruti-ertiga",
    name: "Maruti Ertiga",
    brand: "Maruti",
    model: "Ertiga",
    year: 2024,
    type: "MUV",
    fuelType: "CNG",
    transmission: "Manual",
    engineCC: 1462,
    powerBhp: 86.63,
    torqueNm: 121.5,
    mileageCity: 22.4,
    mileageHighway: 26.2,
    seatingCapacity: 7,
    bootLitres: 209,
    groundClearance: 185,
    priceMin: 869000,
    priceMax: 1330000,
    monthlyService: 2300,
    insuranceYear1: 23000,
    safetyRating: 3,
    depRate1Yr: 0.83,
    depRate3Yr: 0.67,
    depRate5Yr: 0.53,
    imageUrl: "https://5.imimg.com/data5/HX/OP/GLADMIN-13487668/maruti-ertiga-cat.png",
    pros: ["excellent value for large families", "very low running costs", "good comfort for segment"],
    cons: ["safety package is basic", "performance is modest when fully loaded"],
    tags: ["family", "budget", "spacious"]
  },
  {
    slug: "mahindra-scorpio-n",
    name: "Mahindra Scorpio-N",
    brand: "Mahindra",
    model: "Scorpio-N",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 2198,
    powerBhp: 172.45,
    torqueNm: 400,
    mileageCity: 12.4,
    mileageHighway: 15.9,
    seatingCapacity: 7,
    bootLitres: 460,
    groundClearance: 187,
    priceMin: 1399000,
    priceMax: 2454000,
    monthlyService: 4100,
    insuranceYear1: 42000,
    safetyRating: 5,
    depRate1Yr: 0.8,
    depRate3Yr: 0.62,
    depRate5Yr: 0.46,
    imageUrl: "https://imgd.aeplcdn.com/1920x1080/n/cw/ec/40432/scorpio-n-exterior-right-front-three-quarter-4.png?isig=0&q=80&q=80",
    pros: ["strong road presence", "powerful engines", "good offroad capability", "robust build"],
    cons: ["body roll at speed", "fit and finish can vary"],
    tags: ["offroad", "family", "highway"]
  },
  {
    slug: "jeep-meridian",
    name: "Jeep Meridian",
    brand: "Jeep",
    model: "Meridian",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168,
    torqueNm: 350,
    mileageCity: 12.6,
    mileageHighway: 15.8,
    seatingCapacity: 7,
    bootLitres: 481,
    groundClearance: 214,
    priceMin: 3150000,
    priceMax: 3879000,
    monthlyService: 5600,
    insuranceYear1: 54000,
    safetyRating: 5,
    depRate1Yr: 0.76,
    depRate3Yr: 0.57,
    depRate5Yr: 0.42,
    imageUrl: "https://images.timesdrive.in/photo/msid-151013918,thumbsize-434500/151013918.jpg",
    pros: ["premium cabin finish", "proper suv stance", "stable highway behavior", "good safety kit"],
    cons: ["expensive to own", "third row best for children"],
    tags: ["luxury", "highway", "family"]
  },
  {
    slug: "tata-safari",
    name: "Tata Safari",
    brand: "Tata",
    model: "Safari",
    year: 2024,
    type: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCC: 1956,
    powerBhp: 168,
    torqueNm: 350,
    mileageCity: 13,
    mileageHighway: 16.3,
    seatingCapacity: 7,
    bootLitres: 420,
    groundClearance: 205,
    priceMin: 1619000,
    priceMax: 2769000,
    monthlyService: 4300,
    insuranceYear1: 44000,
    safetyRating: 5,
    depRate1Yr: 0.79,
    depRate3Yr: 0.61,
    depRate5Yr: 0.45,
    imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdARTKGho4ToEgLpEkaP7hjttGu88vxLP4_A&s",
    pros: ["captain-seat option", "5-star safety", "feature rich top trims", "strong highway comfort"],
    cons: ["third row space is average", "diesel-only lineup"],
    tags: ["family", "spacious", "highway"]
  },
  {
    slug: "skoda-kushaq",
    name: "Skoda Kushaq",
    brand: "Skoda",
    model: "Kushaq",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1498,
    powerBhp: 147.51,
    torqueNm: 250,
    mileageCity: 14.7,
    mileageHighway: 18.6,
    seatingCapacity: 5,
    bootLitres: 385,
    groundClearance: 188,
    priceMin: 1089000,
    priceMax: 1880000,
    monthlyService: 3500,
    insuranceYear1: 36000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.6,
    depRate5Yr: 0.44,
    imageUrl: "https://cdn.skoda-auto.com/images/external/a720b3257fb9f34c9f582f866b15d4b7/DerivativeIntroductionModule/517a7c8aa96236dc9d8954f4916e42718d6bf87515b75d7ab74272b3bc3277bf/Default_bp1920_1.webp",
    pros: ["excellent driving dynamics", "strong safety package", "punchy turbo engines", "good highway confidence"],
    cons: ["rear seat is not the widest", "service cost is above average"],
    tags: ["sporty", "highway", "luxury"]
  },
  {
    slug: "hyundai-tucson",
    name: "Hyundai Tucson",
    brand: "Hyundai",
    model: "Tucson",
    year: 2024,
    type: "SUV",
    fuelType: "Petrol",
    transmission: "Automatic",
    engineCC: 1999,
    powerBhp: 154.8,
    torqueNm: 192,
    mileageCity: 11.9,
    mileageHighway: 14.8,
    seatingCapacity: 5,
    bootLitres: 540,
    groundClearance: 192,
    priceMin: 2963000,
    priceMax: 3587000,
    monthlyService: 5200,
    insuranceYear1: 53000,
    safetyRating: 5,
    depRate1Yr: 0.77,
    depRate3Yr: 0.58,
    depRate5Yr: 0.43,
    imageUrl: "https://hips.hearstapps.com/hmg-prod/images/2026-hyundai-tucson-hybrid-pr-101-68a38aa37ded6.jpg?crop=0.682xw:0.576xh;0.129xw,0.338xh&resize=1200:*",
    pros: ["premium global design", "very comfortable cabin", "good adas package", "large boot space"],
    cons: ["high initial price", "fuel efficiency is average"],
    tags: ["luxury", "family", "highway"]
  },
  {
    slug: "tata-nexon-ev",
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 143,
    torqueNm: 215,
    mileageCity: 330,
    mileageHighway: 270,
    seatingCapacity: 5,
    bootLitres: 350,
    groundClearance: 190,
    priceMin: 1299000,
    priceMax: 1749000,
    monthlyService: 2100,
    insuranceYear1: 32000,
    safetyRating: 5,
    depRate1Yr: 0.78,
    depRate3Yr: 0.58,
    depRate5Yr: 0.41,
    imageUrl: "https://imgd-ct.aeplcdn.com/664x415/n/cw/ec/149311/nexon-ev-right-front-three-quarter-5.jpeg?isig=0&q=80",
    pros: ["low running cost", "instant torque performance", "good city range", "5-star safety"],
    cons: ["charging network still growing", "highway range drops noticeably"],
    tags: ["ev", "city", "family"]
  },
  {
    slug: "mg-zs-ev",
    name: "MG ZS EV",
    brand: "MG",
    model: "ZS EV",
    year: 2024,
    type: "SUV",
    fuelType: "Electric",
    transmission: "Automatic",
    engineCC: null,
    powerBhp: 174.33,
    torqueNm: 280,
    mileageCity: 390,
    mileageHighway: 320,
    seatingCapacity: 5,
    bootLitres: 448,
    groundClearance: 177,
    priceMin: 1898000,
    priceMax: 2498000,
    monthlyService: 2400,
    insuranceYear1: 41000,
    safetyRating: 5,
    depRate1Yr: 0.76,
    depRate3Yr: 0.56,
    depRate5Yr: 0.4,
    imageUrl: "https://stimg.cardekho.com/images/carexteriorimages/930x620/MG/ZS-EV/6873/1612778753498/front-left-side-47.jpg",
    pros: ["strong real-world range", "premium feature list", "quick acceleration", "comfortable family suv"],
    cons: ["higher upfront cost", "service footprint smaller than mass brands"],
    tags: ["ev", "luxury", "family"]
  }
];

async function main() {
  await prisma.savedCar.deleteMany();
  await prisma.car.deleteMany();

  await prisma.car.createMany({
    data: cars
  });

  console.log(`Seeded ${cars.length} cars`);
}

main()
  .catch((error) => {
    console.error("Seeding failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
